

package nutki;

import java.awt.event.KeyEvent;

/**
 *
 * @author Rino
 */
public class OkienkoWpisu extends javax.swing.JFrame {

    
    int s,w,sx,sy;

    /**
     *
     * @param szerokosc
     * @param wysokosc
     * @param srodekx
     * @param srodeky
     */
    public OkienkoWpisu(int szerokosc, int wysokosc, int srodekx, int srodeky) {
            s=szerokosc;
            w=wysokosc;
            sx=srodekx;
            sy=srodeky;   
       
            initComponents();
            setTitle("Uciekające Nutki"); 
            setLocation((srodekx+300),100); 
            //setUndecorated
            setResizable(false); 
            jTextField3.selectAll();
           jTextField3.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setText("Graj");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 290, 90, 30);

        jTextField3.setText("Gracz");
        jTextField3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField3KeyPressed(evt);
            }
        });
        jPanel1.add(jTextField3);
        jTextField3.setBounds(120, 260, 140, 20);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(200, 250, 100));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jTextArea1.setRows(6);
        jTextArea1.setText("\t Witam w grze uciekające nutki!!         \n\t    \n\t            INSTRUKCJA GRY:   \n\t\n   Gracz ma za zadanie przeprowadzić 15 nutek przez rzekę. \n   Jeśli zostanie utopionych 5 rozgrywaka się kończy. Gra \n   odbywa się na 3 poziomach trudności. Na każdy kolejny \n   można awansować z poprzedniego \n\n\n                   Poniżej podaj swoje imię i rozpocznij grę.           \n\t       \n\t              POWODZENIA!!!!");
        jTextArea1.setBorder(null);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(20, 10, 340, 220);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nutki/image/rzeka1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 530, 380);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 379, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            dispose();
          Elementy.nazwa= jTextField3.getText();
          Okienko ok=new Okienko(s,w,sx,sy); 
          ok.setDefaultCloseOperation(Okienko.EXIT_ON_CLOSE);        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField3KeyPressed
 if(evt.getKeyChar() == KeyEvent.VK_ENTER){
                        dispose();
                        Elementy.nazwa=  jTextField3.getText();
                        Okienko ok=new Okienko(s,w,sx,sy); 
                        ok.setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE); 
                  }              
    }//GEN-LAST:event_jTextField3KeyPressed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables


}






